pathname <- tempfile()
print(pathname)
cat("Hello", file = pathname)
print(file.info(pathname))
print(file.exists(pathname))
print(file_test("-f", pathname))
bfr <- readLines(pathname)
print(bfr)
stopifnot(file_test("-f", pathname))
